### ISSUE TITLE
Does not appear to work in github actions

### ISSUE THREAD

**Issue by Wazbat** [Decathlon/newman-reporter-pullrequest-decorator#8]
Hi there! This reporter looks super useful and would be great for making postman tests easier to see

I've tried using this in github actions however, and newman says it can't see the reporter?

I've tried both the name in the readme and the name of the package (in case there was a mistake) but neither work
```
newman: could not find "@decathlon/newman-reporter-pullrequest-decorator" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm
```
```
newman: could not find "@decathlon/pullrequest-decorator" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm
```

I'm trying to use it like this in my action
```yaml
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i -g @decathlon/newman-reporter-pullrequest-decorator
      - name: Run integration tests
        run: >
          newman run https://api.getpostman.com/collections/blah
          --verbose
          -r cli,@decathlon/newman-reporter-pullrequest-decorator
          --reporter-export ./postman_output.md
```

**Comment by rbenhaddou** [comment]
Hello @Wazbat,

Happy to know it could be useful to you !

I'll try to reproduce it from my side and let you know before end of this week.

**Comment by rbenhaddou** [comment]
I haven't been able to reproduce your issue, on my side it works fine (just got an error saying the collection cannot be loaded)

Basically i've reused your example and just changed two things : 
- Adding newman to be installed globally
- Removing cache: 'npm' (it was throwing the following error : _Dependencies lock file is not found_)

```

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm i -g @decathlon/newman-reporter-pullrequest-decorator
          npm i -g newman
      - name: Run integration tests
        run: >
          newman run https://api.getpostman.com/collections/blah
          --verbose
          -r cli,@decathlon/newman-reporter-pullrequest-decorator
          --reporter-export ./postman_output.md

```

Can you retry without the cache part and let me know ?

**Comment by rbenhaddou** [comment]
Hello @Wazbat,

Hopefully the solution worked for you !

i'll have to close the issue if i don't get any answer before Wednseday.

Thank you for your understanding.

**Comment by Wazbat** [comment]
Hi @rbenhaddou ! Sorry for not replying there

I haven't had a chance to try it yet, but I suspect the reason that this solution works is due to the addition of `npm i -g newman`.

I'm using the standard ubuntu runner, which according to the documentation already has newman installed

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

However, it looks like whatever way it is installed, means it doesn't support global reporters like this. I think installing newman yourself via npm seperately from the included version is a prerequisite to use this. Perhaps this detail should be included in the readme

I do really appreciate your time checking this though!

**Comment by rbenhaddou** [comment]
@Wazbat  It's weird because i just did a test without installing globally newman and it worked (see execution below) : 

```
jobs:
  test:
    name: "newman-reporter"
    timeout-minutes: 10
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm i -g @decathlon/newman-reporter-pullrequest-decorator
      - name: Run integration tests
        run: >
          newman run https://api.getpostman.com/collections/blah
          --verbose
          -r cli,@decathlon/newman-reporter-pullrequest-decorator
          --reporter-export ./postman_output.md

```
<img width="1282" alt="Screenshot 2023-03-30 at 17 59 38" src="https://user-images.githubusercontent.com/45691655/228910621-0b86c63a-3d7f-469f-b9d0-44566afd1c64.png">

Let me know if i can help further, i keep the issue open for a couple of days if you want to add something !
